import { StochMacdOptions } from './bot';

export const ETHUSDT: StochMacdOptions = {
    instrumentType: 'SPOT',
    fee: 0.0003,
    lotsMultiplier: 1,
    equityLevel: 1,
    broker: 'binance',
    ticker: 'ETHUSDT',
    currency: 'USDT',
    interval: '15min',
    amount: 500,
    stopLoss: 3.78,
    takeProfit: 3.87,
    periodEmaFast: 14,
    periodEmaSlow: 16,
    periodSignal: 5,
    stochPeriod: 25,
    stochSmaPeriod: 8,
    signalLife: 1,
    id: 4,
};

export const TSLA: StochMacdOptions = {
    broker: 'alpaca',
    ticker: 'TSLA',
    currency: 'USD',
    interval: '1h',
    amount: 1000,
    stopLoss: 3.93,
    takeProfit: 4.78,
    periodEmaFast: 9,
    periodEmaSlow: 16,
    periodSignal: 10,
    stochPeriod: 19,
    stochSmaPeriod: 12,
    signalLife: 5,
    id: 4,
};

export const TRXUSDT: StochMacdOptions = {
    instrumentType: 'SPOT',
    fee: 0.0003,
    lotsMultiplier: 1,
    equityLevel: 1,
    broker: 'binance',
    ticker: 'TRXUSDT',
    currency: 'USDT',
    interval: '1min',
    amount: 98,
    stopLoss: 2.93,
    takeProfit: 4.96,
    periodEmaFast: 7,
    periodEmaSlow: 25,
    periodSignal: 14,
    stochPeriod: 17,
    stochSmaPeriod: 5,
    signalLife: 3,
    id: 4
};

// export const TRXUSDT: StochMacdOptions = {
//     instrumentType: 'SPOT',
//     fee: 0.0003,
//     lotsMultiplier: 1,
//     equityLevel: 1,
//     broker: 'binance',
//     ticker: 'TRXUSDT',
//     currency: 'USDT',
//     interval: '15min',
//     amount: 98,
//     stopLoss: 4.39,
//     takeProfit: 4.99,
//     periodEmaFast: 12,
//     periodEmaSlow: 21,
//     periodSignal: 14,
//     stochPeriod: 17,
//     stochSmaPeriod: 6,
//     signalLife: 2,
//     id: 0,
// };

















// [
//     {
//         config: {
//             instrumentType: 'SPOT',
//             fee: 0.0003,
//             lotsMultiplier: 1,
//             equityLevel: 1,
//             broker: 'binance',
//             ticker: 'TRXUSDT',
//             currency: 'USDT',
//             interval: '1min',
//             amount: 98,
//             stopLoss: 3.56,
//             takeProfit: 4.85,
//             periodEmaFast: 5,
//             periodEmaSlow: 11,
//             periodSignal: 12,
//             stochPeriod: 9,
//             stochSmaPeriod: 5,
//             signalLife: 4,
//             id: 0
//         },
//         stats: {
//             startBalance: 98,
//             balance: 107.7,
//             maxBalance: 107.7,
//             minBalance: 98,
//             maxMarginUsage: 98,
//             profit: 9.7,
//             long: 2,
//             longRight: 2,
//             short: 1,
//             shortRight: 0,
//             absoluteDD: 0,
//             relativeDD: 0,
//             potentialDD: 0,
//             maxWin: 4.99,
//             maxLoose: 0,
//             profitProb: 0.67,
//             looseProb: 0.33,
//             avgProfit: 4.85,
//             avgLoose: 0,
//             expectation: 3.23,
//             failLine: 0,
//             rightLine: 2,
//             avgFailLine: null,
//             avgRightLine: 0,
//             ticksHandled: 10080,
//             candlesHandled: 10079
//         }
//     },
//     {
//         config: {
//             instrumentType: 'SPOT',
//             fee: 0.0003,
//             lotsMultiplier: 1,
//             equityLevel: 1,
//             broker: 'binance',
//             ticker: 'TRXUSDT',
//             currency: 'USDT',
//             interval: '1min',
//             amount: 98,
//             stopLoss: 3.56,
//             takeProfit: 4.85,
//             periodEmaFast: 9,
//             periodEmaSlow: 11,
//             periodSignal: 7,
//             stochPeriod: 9,
//             stochSmaPeriod: 5,
//             signalLife: 4,
//             id: 1
//         },
//         stats: {
//             startBalance: 98,
//             balance: 107.7,
//             maxBalance: 107.7,
//             minBalance: 98,
//             maxMarginUsage: 98,
//             profit: 9.7,
//             long: 2,
//             longRight: 2,
//             short: 1,
//             shortRight: 0,
//             absoluteDD: 0,
//             relativeDD: 0,
//             potentialDD: 0,
//             maxWin: 4.99,
//             maxLoose: 0,
//             profitProb: 0.67,
//             looseProb: 0.33,
//             avgProfit: 4.85,
//             avgLoose: 0,
//             expectation: 3.23,
//             failLine: 0,
//             rightLine: 2,
//             avgFailLine: null,
//             avgRightLine: 0,
//             ticksHandled: 10080,
//             candlesHandled: 10079
//         }
//     },
//     {
//         config: {
//             instrumentType: 'SPOT',
//             fee: 0.0003,
//             lotsMultiplier: 1,
//             equityLevel: 1,
//             broker: 'binance',
//             ticker: 'TRXUSDT',
//             currency: 'USDT',
//             interval: '1min',
//             amount: 98,
//             stopLoss: 3.56,
//             takeProfit: 4.85,
//             periodEmaFast: 6,
//             periodEmaSlow: 11,
//             periodSignal: 12,
//             stochPeriod: 9,
//             stochSmaPeriod: 5,
//             signalLife: 4,
//             id: 2
//         },
//         stats: {
//             startBalance: 98,
//             balance: 107.69,
//             maxBalance: 107.69,
//             minBalance: 98,
//             maxMarginUsage: 98,
//             profit: 9.69,
//             long: 2,
//             longRight: 2,
//             short: 1,
//             shortRight: 0,
//             absoluteDD: 0,
//             relativeDD: 0,
//             potentialDD: 0,
//             maxWin: 4.98,
//             maxLoose: 0,
//             profitProb: 0.67,
//             looseProb: 0.33,
//             avgProfit: 4.85,
//             avgLoose: 0,
//             expectation: 3.23,
//             failLine: 0,
//             rightLine: 2,
//             avgFailLine: null,
//             avgRightLine: 0,
//             ticksHandled: 10080,
//             candlesHandled: 10079
//         }
//     },
//     {
//         config: {
//             instrumentType: 'SPOT',
//             fee: 0.0003,
//             lotsMultiplier: 1,
//             equityLevel: 1,
//             broker: 'binance',
//             ticker: 'TRXUSDT',
//             currency: 'USDT',
//             interval: '1min',
//             amount: 98,
//             stopLoss: 3.56,
//             takeProfit: 4.85,
//             periodEmaFast: 6,
//             periodEmaSlow: 11,
//             periodSignal: 12,
//             stochPeriod: 9,
//             stochSmaPeriod: 5,
//             signalLife: 4,
//             id: 3
//         },
//         stats: {
//             startBalance: 98,
//             balance: 107.69,
//             maxBalance: 107.69,
//             minBalance: 98,
//             maxMarginUsage: 98,
//             profit: 9.69,
//             long: 2,
//             longRight: 2,
//             short: 1,
//             shortRight: 0,
//             absoluteDD: 0,
//             relativeDD: 0,
//             potentialDD: 0,
//             maxWin: 4.98,
//             maxLoose: 0,
//             profitProb: 0.67,
//             looseProb: 0.33,
//             avgProfit: 4.85,
//             avgLoose: 0,
//             expectation: 3.23,
//             failLine: 0,
//             rightLine: 2,
//             avgFailLine: null,
//             avgRightLine: 0,
//             ticksHandled: 10080,
//             candlesHandled: 10079
//         }
//     },
//     {
//         config: {
//             instrumentType: 'SPOT',
//             fee: 0.0003,
//             lotsMultiplier: 1,
//             equityLevel: 1,
//             broker: 'binance',
//             ticker: 'TRXUSDT',
//             currency: 'USDT',
//             interval: '1min',
//             amount: 98,
//             stopLoss: 3.56,
//             takeProfit: 4.85,
//             periodEmaFast: 6,
//             periodEmaSlow: 11,
//             periodSignal: 12,
//             stochPeriod: 9,
//             stochSmaPeriod: 5,
//             signalLife: 4,
//             id: 4
//         },
//         stats: {
//             startBalance: 98,
//             balance: 107.69,
//             maxBalance: 107.69,
//             minBalance: 98,
//             maxMarginUsage: 98,
//             profit: 9.69,
//             long: 2,
//             longRight: 2,
//             short: 1,
//             shortRight: 0,
//             absoluteDD: 0,
//             relativeDD: 0,
//             potentialDD: 0,
//             maxWin: 4.98,
//             maxLoose: 0,
//             profitProb: 0.67,
//             looseProb: 0.33,
//             avgProfit: 4.85,
//             avgLoose: 0,
//             expectation: 3.23,
//             failLine: 0,
//             rightLine: 2,
//             avgFailLine: null,
//             avgRightLine: 0,
//             ticksHandled: 10080,
//             candlesHandled: 10079
//         }
//     }
// ]
